# Generated by Django 2.2.2 on 2019-08-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puple',
            name='lname',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
