# Generated by Django 2.2.2 on 2019-08-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp1', '0002_auto_20190819_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gend', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='puple',
            name='genderf',
            field=models.ManyToManyField(related_name='gender_relname', to='schoolapp1.gender'),
        ),
    ]
